# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

title: blank
first_name: Rui
middle_name:
last_name: Sun
email: eruisun at stanford dot edu
description:
keywords:
lang: en
icon:

url: https://sr-11.github.io
baseurl:
last_updated: false
impressum_path:
back_to_top: true

footer_text: >
  Powered by <a href="https://jekyllrb.com/" target="_blank">Jekyll</a> with <a href="https://github.com/alshedivat/al-folio">al-folio</a> theme.

# -----------------------------------------------------------------------------
# Layout
# -----------------------------------------------------------------------------

navbar_fixed: true
footer_fixed: true
max_width: 930px

# -----------------------------------------------------------------------------
# Social links
# -----------------------------------------------------------------------------

scholar_userid: DNoO_lYAAAAJ
contact_note:

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

markdown: kramdown

include: ["_pages"]
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - vendor

plugins:
  - jekyll-email-protect
  - jekyll-link-attributes
  - jekyll-sitemap

defaults:
  - scope:
      path: "assets"
    values:
      sitemap: false

sass:
  style: compressed

external_links:
  enabled: true
  rel: external nofollow noopener
  target: _blank
  exclude:

imagemagick:
  enabled: false

lazy_loading_images: true

# -----------------------------------------------------------------------------
# Third-party libraries
# -----------------------------------------------------------------------------

third_party_libraries:
  google_fonts:
    url:
      fonts: "https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:100,300,400,500,700|Material+Icons&display=swap"
  jquery:
    integrity:
      js: "sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
    url:
      js: "https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.min.js"
  mdb:
    integrity:
      css: "sha256-jpjYvU3G3N6nrrBwXJoVEYI/0zw8htfFnhT9ljN3JJw="
      js: "sha256-NdbiivsvWt7VYCt6hYNT3h/th9vSTL4EDWeGs5SN3DA="
    url:
      css: "https://cdn.jsdelivr.net/npm/mdbootstrap@4.20.0/css/mdb.min.css"
      js: "https://cdn.jsdelivr.net/npm/mdbootstrap@4.20.0/js/mdb.min.js"
