title: Rui Sun
description: I'm Rui Sun, an MIT undergraduate majoring in mathematics and physics. Prior to this, I was an undergraduate at Peking University. My interests lie broadly in machine learning.
keywords: Rui Sun, MIT, mathematics, physics, machine learning, Peking University, undergraduate, TCS, probability, theory, statistics, 

